config/routes.rb
Online::Application.routes.draw do
  resources :advertises

  resources :posts
  
  resources :hellos

  get "home/index"

  root :to => 'home#index'

end

app/models/advertise.rb
class Advertise < ActiveRecord::Base

  attr_accessible :content, :image, :title

  validates :content, :length => {:minimum => 10, :maximum => 1000}
  validates :title, :uniqueness => {:in => true, :message => "its must not use before"}, :length => {:minimum => 5, :maximum => 50}
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :name, :title

  validates :name, :length => {:in => 5..100}, :presence => {:in => true, :message => "its cannot blank"}, :uniqueness => {:in => true, :message => "is already used before"}
end

app/controllers/advertises_controller.rb
class AdvertisesController < ApplicationController
  # GET /advertises
  # GET /advertises.json
  def index
    @advertises = Advertise.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @advertises }
    end
  end

  # GET /advertises/1
  # GET /advertises/1.json
  def show
    @advertise = Advertise.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @advertise }
    end
  end

  # GET /advertises/new
  # GET /advertises/new.json
  def new
    @advertise = Advertise.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @advertise }
    end
  end

  # GET /advertises/1/edit
  def edit
    @advertise = Advertise.find(params[:id])
  end

  # POST /advertises
  # POST /advertises.json
  def create
    @advertise = Advertise.new(params[:advertise])

    respond_to do |format|
      if @advertise.save
        format.html { redirect_to @advertise, notice: 'Advertise was successfully created.' }
        format.json { render json: @advertise, status: :created, location: @advertise }
      else
        format.html { render action: "new" }
        format.json { render json: @advertise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /advertises/1
  # PUT /advertises/1.json
  def update
    @advertise = Advertise.find(params[:id])

    respond_to do |format|
      if @advertise.update_attributes(params[:advertise])
        format.html { redirect_to @advertise, notice: 'Advertise was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @advertise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advertises/1
  # DELETE /advertises/1.json
  def destroy
    @advertise = Advertise.find(params[:id])
    @advertise.destroy

    respond_to do |format|
      format.html { redirect_to advertises_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper :all
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
 #include HelloHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/advertises_helper.rb
module AdvertisesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
 def hello
  puts "Hello from my app, it's my testing first"
 end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/advertises/_form.html.erb
<%= form_for(@advertise) do |f| %>
  <% if @advertise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@advertise.errors.count, "error") %> prohibited this advertise from being saved:</h2>

      <ul>
      <% @advertise.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/advertises/edit.html.erb
<h1>Editing advertise</h1>

<%= render 'form' %>

<%= link_to 'Show', @advertise %> |
<%= link_to 'Back', advertises_path %>

app/views/advertises/index.html.erb
<h1>Listing advertises</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Image</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @advertises.each do |advertise| %>
  <tr>
    <td><%= advertise.title %></td>
    <td><%= advertise.content %></td>
    <td><%= advertise.image %></td>
    <td><%= link_to 'Show', advertise %></td>
    <td><%= link_to 'Edit', edit_advertise_path(advertise) %></td>
    <td><%= link_to 'Destroy', advertise, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Advertise', new_advertise_path %>

app/views/advertises/new.html.erb
<h1>New advertise</h1>

<%= render 'form' %>

<%= link_to 'Back', advertises_path %>

app/views/advertises/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @advertise.title %>
</p>

<p>
  <b>Content:</b>
  <%= @advertise.content %>
</p>

<p>
  <b>Image:</b>
  <%= @advertise.image %>
</p>


<%= link_to 'Edit', edit_advertise_path(@advertise) %> |
<%= link_to 'Back', advertises_path %>

app/views/hello/index.html.erb
<%= hello %>

app/views/home/index.html.erb
<h1>Welcome in my app</h1>

<%= link_to "Posting Now", posts_path%> <br />
<%= link_to "Advertises", advertises_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Online</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.name %></td>
    <td><%= post.title %></td>
    <td><%= post.content %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @post.name %>
</p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>